FROM postgres:15-alpine

COPY init.sql /docker-entrypoint-initdb.d/01-init.sql
COPY init-admin.sh /docker-entrypoint-initdb.d/02-init-admin.sh

RUN chmod +x /docker-entrypoint-initdb.d/02-init-admin.sh
